### ISSUE TITLE
0.0.10---double key spawn

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#189] opened 2018-12-09 17:54 UTC
Double Trouble room---each enemy of the pair spawned a key.

**Comment by drrich** [comment] 2018-12-09 18:11
Update:  previous error reported on 0.0.11, but I think it's actually 0.0.10 as my Linux machine (Manjaro) was not up to date.

**Comment by ChrisNZL** [comment] 2018-12-10 03:56
Dupe of #173, should be fixed in v0.0.11, no worries thanks :)

**Closed by ChrisNZL** 2018-12-10 03:56 UTC
Labels: duplicate
