### ISSUE TITLE
Quick weapon switching fails

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#125] opened 2018-11-02 01:45 UTC
0.0.8:  Occasionally when I pick up a new weapon, I am unable to quick switch weapons.  Opening inventory and equipping a different weapon restores functionality.  (Keyboard, Linux, 'Axeboy' on Discord)

**Comment by ChrisNZL** [comment] 2018-11-02 03:10
Thanks for reporting. Able to reproduce. Steps:
1. Start new game.
2. Open the dev console with <kbd>~</kbd> and type dev command: `rarity 2` and select the first result.
3. Type dev command: `chest axe` and select the first result. A chest will spawn.
4. Loot the chest with the blue Axe. The new Axe becomes equipped.
5. Press Up to switch to your white Bow.
6. Walk to an empty space, type dev command: `chest bow`, select the first result. A chest will spawn.
7. Loot the chest with the blue Bow. This triggers the issue, an am unable to press Up/Down to quickly switch weapons anymore.

Underlying bug seems to be: If a chest has a weapon whose attack power is equal to your most-powerful weapon's attack power, _and_ you have a lesser version of the same type of weapon currently equipped that the chest contains, acquiring the weapon from the chest stuffs up the acquiring/insertion quickness somewhere.

**Comment by ChrisNZL** [comment] 2018-11-03 08:10
Fixed in v0.0.9. Thanks again.

**Closed by ChrisNZL** 2018-11-03 08:10 UTC
Labels: bug
